### ISSUE TITLE
no transcription 

### ISSUE THREAD

**Issue by rahulkathet** [asterisk/asterisk-external-media#11]
Getting below when after I receive call on one of ext. but no transcription
Do you know what could be the reason?

Creating Bridge and Channels
server listening 127.0.0.1:4443
Processing

25000: RESTARTING REQUEST

**Comment by psanders** [comment]
I was having that issue with `asterisk-18.2.1-r1@alpine-3.13` on Docker. I switched to  `16.16.1-r0@alpine-3.11`. I'm not sure why. Perhaps some API change?

**Comment by rahulkathet** [comment]
Wanted to implement it in the code, using AMI and AGI now direct API.

**Comment by rahulkathet** [comment]
> I was having that issue with `asterisk-18.2.1-r1@alpine-3.13` on Docker. I switched to `16.16.1-r0@alpine-3.12` and it started working. I'm not sure why. Perhaps some API change?

thank you for help.

**Comment by jneuendorf-i4h** [comment]
@gtjoseph Could the Asterisk version be a plausible cause? I looked through the changelog but couldn't find any ARI related breaking changes. In my case, everything seems to be fine but the audio server running locally (host) just doesn't receive any packages from Asterisk running within Docker.
