### ISSUE TITLE
Dialplan example 

### ISSUE THREAD

**Issue by warawich** [asterisk/asterisk-external-media#2]
Hello,

This is not issue. I tried to start the application. I don't know how to configure the dialplan to call the application. 
Cloud you please advise me? 

This is extension.conf

exten = 2000,1,NoOp()
same  = n,Set(TALK_DETECT(set)=3000,100)
same  = n,Answer()
same  = n,Stasis(local,0001234965,p,0|0)
same  = n,Hangup()

Command 
bin/ari-transcriber --format="ulaw" "local/2000"

Asterisk Log
 Creating Stasis app 'externalMedia'
  == WebSocket connection from '127.0.0.1:55072' for protocol '' accepted using version '13'
[Feb 28 16:26:13] NOTICE[25961]: core_local.c:734 local_call: No such extension/context 2000@default while calling Local channel
    -- Called 127.0.0.1:9999
    -- UnicastRTP/127.0.0.1:9999-0x7f4e90010a30 answered
    -- Channel UnicastRTP/127.0.0.1:9999-0x7f4e90010a30 joined 'simple_bridge' stasis-bridge <b8fd3273-00a0-460d-bc4d-ab01aff98edd>

Thanks,
Warawich

**Comment by gtjoseph** [comment]
The application was designed to demonstrate dialing out to an extension or into an existing conference bridge and transcribing the audio to text.  You don't need any special dialplan entries to use it.

**Comment by nattapote** [comment]
Hi Gtjoseph,

Thank you for advised. It is works now.

Best regards,
Warawich

**Comment by warawich** [comment]
Hi Gtjoseph,

Thank you for advised. It works now.

Best regards,
Warawich
