### ISSUE TITLE
How can I identify the transcription using a custom variable

### ISSUE THREAD

**Issue by habibshahid** [asterisk/asterisk-external-media#24]
Hello,

Thank you for the great work. I wanted to know how to identify the transcription via some custom ID. There will be multiple calls going on, the idea is to save the transcription with every unique call. I am unable to sort this out. Perhaps can get some help from the experts.

Please advise.
Thank you

**Comment by jcolp** [comment]
This question is a better fit for the APIs category on the Asterisk forum at https://community.asterisk.org/ as it's an implementation detail of the ARI application, and not really to do with this sample.

**Comment by habibshahid** [comment]
I am sorry I may not have been able to explain myself. I am generating unique bridge IDs and I have that information already available. But since the stream is sent on a remote port and this application does the transcription. I was curious how can I identify the transcription belongs to which Bridge.

**Comment by jcolp** [comment]
Each external media uses a separate port, you associate that port with the respective information in the ARI application and use that information as you wish.
