### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by thanhuchiha** [asterisk/asterisk-external-media#6]
I tried to run it but got an error like this ( run code with comand : node bin/ari-transcriber --format=slin16 'Local/1170' ): 
Creating ARI Controller to Asterisk instance http://127.0.0.1:8080
Starting audio listener on 127.0.0.1:9999
Starting speech provider
Creating Bridge and Channels
server listening 127.0.0.1:9999
(node:2659) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:2659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Please help me !

**Comment by gtjoseph** [comment]
The actual issue is `(node:2659) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8080`.
By default, Asterisk listens on port 8088 not port 8080.

**Comment by thanhuchiha** [comment]
i tried again: 
Creating ARI Controller to Asterisk instance http://127.0.0.1:8088
Starting audio listener on 127.0.0.1:9999
Starting speech provider
Creating Bridge and Channels
server listening 127.0.0.1:9999
(node:1508) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8088
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:1508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Help me :((((
Where did I go wrong?

**Comment by gtjoseph** [comment]
Do you have Asterisk configured to listen on port 8088? 
I'd suggest following the instructions in the link below to get Asterisk configured for ARI...
https://wiki.asterisk.org/wiki/display/AST/Asterisk+Configuration+for+ARI

**Comment by thanhuchiha** [comment]
@gtjoseph 
I adjusted the port 8088 and configured for ARI follow the link above. When i call node bin/ari-transcriber --format=slin16 'Local/1234'.Then call with number 1234. 
It returns like this : 
Creating ARI Controller to Asterisk instance http://127.0.0.1:8088
Starting audio listener on 127.0.0.1:9999
Starting speech provider
Creating Bridge and Channels
server listening 127.0.0.1:9999
send: reset nghttp2_active_outbound_item
send: aob->item = (nil)
recv: connection recv_window_size=0, local_window=65535
stream: adjusting kept idle streams num_idle_streams=0, max=100
recv: [IB_READ_FIRST_SETTINGS]
recv: [IB_READ_HEAD]
recv: payloadlen=18, type=4, flags=0x00, stream_id=0
recv: SETTINGS
recv: [IB_READ_SETTINGS]
recv: readlen=6, payloadleft=12
recv: [IB_READ_SETTINGS]
....

Why does it not show text after recognition ?
