### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by thanhuchiha** [asterisk/asterisk-external-media#7]
Hi everyone. I tried to configure ARI as this link ( https://wiki.asterisk.org/wiki/display/AST/Asterisk+Configuration+for+ARI ).

![123](https://user-images.githubusercontent.com/32055438/92009757-2ff79c80-ed73-11ea-8fba-def659d0e575.png)

And when running, it doesn't show anything.  I went wrong in the installation step, help me

**Comment by gtjoseph** [comment]
There's no way for us to troubleshoot that error.  "DEADLINE EXCEEDED" is a message from the Google API.  You should consult their documentation for more info.
